### ISSUE TITLE
EDA shows "Error Loading" on everything

### ISSUE THREAD

**Issue by mlowcher61** [ansible-content-lab/aws_ansible_deployment#15]
Everything deployed using this collection but upon logging into EDA it shows "Error Loading" everywhere. It is impossible to do any configuration.

**Comment by scottharwell** [comment]
This sounds like it's out of the scope of what this collection does, which is deploying infrastructure and then running the AAP installer.  Once installed, the behavior of AAP would be troubleshot using AAP logs, configurations, etc. and resolved based on what the error is.  Have you reviewed the EDA logs in the VM on which is was installed to see what errors are being reported.  Unless errors are related to the infrastructure itself, then this would be something to troubleshoot with AAP, and not this collection.

**Comment by mlowcher61** [comment]
I found the issue. If you use the aws dns name you will get this error regardless of browser. If you use the public ip address, all is well. It has to be a certificate issue.

**Comment by scottharwell** [comment]
Take a look at how `automationedacontroller_allowed_hostnames` is applied in the AAP installer.  That's probably what you bumped into.  It can be changed post install, too.  You don't need to redeploy.

https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.4/html-single/red_hat_ansible_automation_platform_installation_guide/index#event-driven-ansible-controller
